# Assignment 3: Predict Abalone Age

### Load the Dataset

In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [57]:
df =pd.read_csv("abalone.csv")

### Display some basic info of the dataset

In [58]:
df.head()

Sex  Length  Diameter  ...  Viscera weight  Shell weight  Rings
0   M   0.455     0.365  ...          0.1010         0.150     15
1   M   0.350     0.265  ...          0.0485         0.070      7
2   F   0.530     0.420  ...          0.1415         0.210      9
3   M   0.440     0.365  ...          0.1140         0.155     10
4   I   0.330     0.255  ...          0.0395         0.055      7

[5 rows x 9 columns]

In [59]:
df.shape

(4177, 9)

In [60]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             4177 non-null   object 
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole weight    4177 non-null   float64
 5   Shucked weight  4177 non-null   float64
 6   Viscera weight  4177 non-null   float64
 7   Shell weight    4177 non-null   float64
 8   Rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


In [62]:
df.sample(5)

Sex  Length  Diameter  ...  Viscera weight  Shell weight  Rings
1310   I   0.545     0.405  ...          0.1185        0.1850      8
3585   M   0.625     0.485  ...          0.2235        0.3020      9
4041   I   0.575     0.450  ...          0.1660        0.2150     10
3698   F   0.650     0.510  ...          0.3155        0.3885     10
2526   M   0.590     0.480  ...          0.2725        0.3350      9

[5 rows x 9 columns]

In [63]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [64]:
df.describe()

Length     Diameter  ...  Shell weight        Rings
count  4177.000000  4177.000000  ...   4177.000000  4177.000000
mean      0.523992     0.407881  ...      0.238831     9.933684
std       0.120093     0.099240  ...      0.139203     3.224169
min       0.075000     0.055000  ...      0.001500     1.000000
25%       0.450000     0.350000  ...      0.130000     8.000000
50%       0.545000     0.425000  ...      0.234000     9.000000
75%       0.615000     0.480000  ...      0.329000    11.000000
max       0.815000     0.650000  ...      1.005000    29.000000

[8 rows x 8 columns]

### Separate the output variable from the dataset

In [65]:
X=df.drop(columns=['Rings'])
X

Sex  Length  Diameter  ...  Shucked weight  Viscera weight  Shell weight
0      M   0.455     0.365  ...          0.2245          0.1010        0.1500
1      M   0.350     0.265  ...          0.0995          0.0485        0.0700
2      F   0.530     0.420  ...          0.2565          0.1415        0.2100
3      M   0.440     0.365  ...          0.2155          0.1140        0.1550
4      I   0.330     0.255  ...          0.0895          0.0395        0.0550
...   ..     ...       ...  ...             ...             ...           ...
4172   F   0.565     0.450  ...          0.3700          0.2390        0.2490
4173   M   0.590     0.440  ...          0.4390          0.2145        0.2605
4174   M   0.600     0.475  ...          0.5255          0.2875        0.3080
4175   F   0.625     0.485  ...          0.5310          0.2610        0.2960
4176   M   0.710     0.555  ...          0.9455          0.3765        0.4950

[4177 rows x 8 columns]

In [66]:
Y=df['Rings']
Y=np.array(Y)
Y

array([15,  7,  9, ...,  9, 10, 12])

### Use OneHotEncoder to transform the column 'Sex'

In [67]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

columnTransformer = ColumnTransformer([('encoder',
                                       OneHotEncoder(),
                                       [0])],
                                       remainder='passthrough')
X=columnTransformer.fit_transform(X)
X


array([[0.    , 0.    , 1.    , ..., 0.2245, 0.101 , 0.15  ],
       [0.    , 0.    , 1.    , ..., 0.0995, 0.0485, 0.07  ],
       [1.    , 0.    , 0.    , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.    , 0.    , 1.    , ..., 0.5255, 0.2875, 0.308 ],
       [1.    , 0.    , 0.    , ..., 0.531 , 0.261 , 0.296 ],
       [0.    , 0.    , 1.    , ..., 0.9455, 0.3765, 0.495 ]])

### Split into training and testing

In [68]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(X,Y,test_size=0.33)

In [69]:
y_train=np.array(y_train)
y_train

array([ 7, 12,  8, ...,  9, 10,  7])

### Train Linear Regression Model

In [70]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
model.score(x_test, y_test)

0.5270830783734024

### Display some scores

In [71]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
# Display R2 Score
r2_score(y_test,y_pred)

0.5270830783734024

In [72]:
# Display Mean Absolute Error
mean_absolute_error(y_test, y_pred)

1.6213699351885424

In [73]:
# Display Mean Squared Error
mean_squared_error(y_test, y_pred)

5.232920820251421

In [74]:
# Display Root Mean Squared Error
np.sqrt(mean_squared_error(y_test, y_pred))

2.287557828832185

### Make some predictions

In [75]:
arr = []
for i in range(0,10):
  arr.append([y_test[i],np.round(y_pred[i])])

print(pd.DataFrame(arr, columns = ['actual value','predicted value']))

   actual value  predicted value
0             3              5.0
1             8              8.0
2            11              6.0
3            11             13.0
4            10              9.0
5            11             11.0
6            10             13.0
7             9             12.0
8            17             13.0
9             9             12.0
